version: '2'

services:
  django:
    container_name: container
    build: 
        context: .
        dockerfile: Dockerfile
    image: docker_tutorial_django
    stdin_open: true
    tty: true
    volumes:
      - .:/code
    ports:
      - "8080:80"
